#undef COIN_MAJOR_VERSION
#undef COIN_MINOR_VERSION
#undef COIN_MICRO_VERSION
#undef COIN_VERSION

#undef HAVE_LIBSIMAGE
#undef HAVE_OPENGL
#undef HAVE_OSMESACREATECONTEXT
#undef HAVE_GLX
#undef HAVE_SNPRINTF
#undef HAVE_VSNPRINTF
#undef HAVE__SNPRINTF
#undef HAVE__VSNPRINTF
#undef HAVE_HASH_QUOTING
#undef HAVE_APOSTROPHES_QUOTING
