#!/bin/sh

cat <<EOF

Error: to bootstrap, invoke the script simacros/bin/bootstrap.

The simacros CVS module can be fetched by doing:

   \$ export CVSROOT=:pserver:cvs@cvs.coin3d.org:/export/cvsroot
   \$ cvs login
   [password is 'cvs']
   \$ cvs checkout simacros


Exiting..

EOF

exit 1
