#include "SoClipPlaneManip.cpp"
#include "SoDirectionalLightManip.cpp"
#include "SoPointLightManip.cpp"
#include "SoSpotLightManip.cpp"
#include "SoTransformManip.cpp"
#include "SoCenterballManip.cpp"
#include "SoHandleBoxManip.cpp"
#include "SoJackManip.cpp"
#include "SoTabBoxManip.cpp"
#include "SoTrackballManip.cpp"
#include "SoTransformBoxManip.cpp"
#include "SoTransformerManip.cpp"

#include "commoncode.cpp"
