# Startup state is global. Each CTest case must run in a fresh process with
# a controlled environment, before SoDB::init() has ever been called.
if(NOT DEFINED TEST_EXECUTABLE OR NOT DEFINED PROFILE_MODE)
  message(FATAL_ERROR "TEST_EXECUTABLE and PROFILE_MODE are required")
endif()
unset(ENV{COIN_PROFILER_OVERLAY})
if(PROFILE_MODE STREQUAL "unset")
  unset(ENV{COIN_PROFILER})
  set(expected 0)
elseif(PROFILE_MODE STREQUAL "off" OR PROFILE_MODE STREQUAL "0")
  set(ENV{COIN_PROFILER} "${PROFILE_MODE}")
  set(expected 0)
elseif(PROFILE_MODE STREQUAL "on" OR PROFILE_MODE STREQUAL "1" OR
       PROFILE_MODE STREQUAL "syncgl")
  set(ENV{COIN_PROFILER} "${PROFILE_MODE}")
  set(expected 1)
elseif(PROFILE_MODE STREQUAL "invalid")
  set(ENV{COIN_PROFILER} "on:pr717_invalid_token")
  set(expected 1)
else()
  message(FATAL_ERROR "Unknown PROFILE_MODE: ${PROFILE_MODE}")
endif()
execute_process(COMMAND "${TEST_EXECUTABLE}" "${expected}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
message("${output}${errors}")
if(NOT "${result}" STREQUAL "0")
  message(FATAL_ERROR "Profiler startup regression failed: ${result}")
endif()
string(REGEX MATCHALL "invalid token 'pr717_invalid_token'" warnings "${errors}")
list(LENGTH warnings warning_count)
if(PROFILE_MODE STREQUAL "invalid")
  if(NOT warning_count EQUAL 1)
    message(FATAL_ERROR "Expected one invalid-token warning, got ${warning_count}")
  endif()
elseif(NOT warning_count EQUAL 0)
  message(FATAL_ERROR "Unexpected invalid-token warning")
endif()
