#include "SoButtonEvent.cpp"
#include "SoEvent.cpp"
#include "SoKeyboardEvent.cpp"
#include "SoLocation2Event.cpp"
#include "SoMotion3Event.cpp"
#include "SoMouseButtonEvent.cpp"
#include "SoSpaceballButtonEvent.cpp"
