/**************************************************************************\
 *
 *  Copyright (C) 1998-2000 by Systems in Motion.  All rights reserved.
 *
 *  This file is part of the Coin library.
 *
 *  This file may be distributed under the terms of the Q Public License
 *  as defined by Troll Tech AS of Norway and appearing in the file
 *  LICENSE.QPL included in the packaging of this file.
 *
 *  If you want to use Coin in applications not covered by licenses
 *  compatible with the QPL, you can contact SIM to aquire a
 *  Professional Edition license for Coin.
 *
 *  Systems in Motion AS, Prof. Brochs gate 6, N-7030 Trondheim, NORWAY
 *  http://www.sim.no/ sales@sim.no Voice: +47 22114160 Fax: +47 67172912
 *
\**************************************************************************/

#include "SoAccumulatedElement.cpp"
#include "SoAmbientColorElement.cpp"
#include "SoAnnoText3CharOrientElement.cpp"
#include "SoAnnoText3FontSizeHintElement.cpp"
#include "SoAnnoText3RenderPrintElement.cpp"
#include "SoBBoxModelMatrixElement.cpp"
#include "SoCacheElement.cpp"
#include "SoClipPlaneElement.cpp"
#include "SoComplexityElement.cpp"
#include "SoComplexityTypeElement.cpp"
#include "SoCoordinateElement.cpp"
#include "SoCreaseAngleElement.cpp"
#include "SoCullElement.cpp"
#include "SoDecimationPercentageElement.cpp"
#include "SoDecimationTypeElement.cpp"
#include "SoDiffuseColorElement.cpp"
#include "SoDrawStyleElement.cpp"
#include "SoElement.cpp"
#include "SoEmissiveColorElement.cpp"
#include "SoEnvironmentElement.cpp"
#include "SoFloatElement.cpp"
#include "SoFocalDistanceElement.cpp"
#include "SoFontNameElement.cpp"
#include "SoFontSizeElement.cpp"
#include "SoGLAmbientColorElement.cpp"
#include "SoGLClipPlaneElement.cpp"
#include "SoGLCoordinateElement.cpp"
#include "SoGLDiffuseColorElement.cpp"
#include "SoGLDrawStyleElement.cpp"
#include "SoGLEmissiveColorElement.cpp"
#include "SoGLEnvironmentElement.cpp"
#include "SoGLLazyElement.cpp"
#include "SoGLLightIdElement.cpp"
#include "SoGLLightModelElement.cpp"
#include "SoGLLinePatternElement.cpp"
#include "SoGLLineWidthElement.cpp"
#include "SoGLModelMatrixElement.cpp"
#include "SoGLNormalElement.cpp"
#include "SoGLNormalizeElement.cpp"
#include "SoGLPointSizeElement.cpp"
#include "SoGLPolygonOffsetElement.cpp"
#include "SoGLPolygonStippleElement.cpp"
#include "SoGLProjectionMatrixElement.cpp"
#include "SoGLRenderPassElement.cpp"
#include "SoGLShadeModelElement.cpp"
#include "SoGLShapeHintsElement.cpp"
#include "SoGLShininessElement.cpp"
#include "SoGLSpecularColorElement.cpp"
#include "SoGLTextureCoordinateElement.cpp"
#include "SoGLTextureEnabledElement.cpp"
#include "SoGLTextureImageElement.cpp"
#include "SoGLTextureMatrixElement.cpp"
#include "SoGLUpdateAreaElement.cpp"
#include "SoGLViewingMatrixElement.cpp"
#include "SoGLViewportRegionElement.cpp"
#include "SoInt32Element.cpp"
#include "SoLazyElement.cpp"
#include "SoLightAttenuationElement.cpp"
#include "SoLightElement.cpp"
#include "SoLightModelElement.cpp"
#include "SoLinePatternElement.cpp"
#include "SoLineWidthElement.cpp"
#include "SoLocalBBoxMatrixElement.cpp"
#include "SoMaterialBindingElement.cpp"
#include "SoModelMatrixElement.cpp"
#include "SoNormalBindingElement.cpp"
#include "SoNormalElement.cpp"
#include "SoOverrideElement.cpp"
#include "SoPROTOElement.cpp"
#include "SoPickRayElement.cpp"
#include "SoPickStyleElement.cpp"
#include "SoPointSizeElement.cpp"
#include "SoPolygonOffsetElement.cpp"
#include "SoProfileCoordinateElement.cpp"
#include "SoProfileElement.cpp"
#include "SoProjectionMatrixElement.cpp"
#include "SoReplacedElement.cpp"
#include "SoShapeHintsElement.cpp"
#include "SoShapeStyleElement.cpp"
#include "SoShininessElement.cpp"
#include "SoSpecularColorElement.cpp"
#include "SoSwitchElement.cpp"
#include "SoTextOutlineEnabledElement.cpp"
#include "SoTextureCoordinateBindingElement.cpp"
#include "SoTextureCoordinateElement.cpp"
#include "SoTextureImageElement.cpp"
#include "SoTextureMatrixElement.cpp"
#include "SoTextureOverrideElement.cpp"
#include "SoTextureQualityElement.cpp"
#include "SoTransparencyElement.cpp"
#include "SoUnitsElement.cpp"
#include "SoViewVolumeElement.cpp"
#include "SoViewingMatrixElement.cpp"
#include "SoViewportRegionElement.cpp"
#include "SoWindowElement.cpp"
