/**************************************************************************\
 *
 *  This file is part of the Coin 3D visualization library.
 *  Copyright (C) 1998-2003 by Systems in Motion.  All rights reserved.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  ("GPL") version 2 as published by the Free Software Foundation.
 *  See the file LICENSE.GPL at the root directory of this source
 *  distribution for additional information about the GNU GPL.
 *
 *  For using Coin with software that can not be combined with the GNU
 *  GPL, and for taking advantage of the additional benefits of our
 *  support services, please contact Systems in Motion about acquiring
 *  a Coin Professional Edition License.
 *
 *  See <URL:http://www.coin3d.org> for  more information.
 *
 *  Systems in Motion, Teknobyen, Abels Gate 5, 7030 Trondheim, NORWAY.
 *  <URL:http://www.sim.no>.
 *
\**************************************************************************/

#include "SoAccumulatedElement.cpp"
#include "SoAmbientColorElement.cpp"
#include "SoAnnoText3CharOrientElement.cpp"
#include "SoAnnoText3FontSizeHintElement.cpp"
#include "SoAnnoText3RenderPrintElement.cpp"
#include "SoBBoxModelMatrixElement.cpp"
#include "SoCacheElement.cpp"
#include "SoClipPlaneElement.cpp"
#include "SoComplexityElement.cpp"
#include "SoComplexityTypeElement.cpp"
#include "SoCoordinateElement.cpp"
#include "SoCreaseAngleElement.cpp"
#include "SoCullElement.cpp"
#include "SoDecimationPercentageElement.cpp"
#include "SoDecimationTypeElement.cpp"
#include "SoDiffuseColorElement.cpp"
#include "SoDrawStyleElement.cpp"
#include "SoElement.cpp"
#include "SoEmissiveColorElement.cpp"
#include "SoEnvironmentElement.cpp"
#include "SoFloatElement.cpp"
#include "SoFocalDistanceElement.cpp"
#include "SoFontNameElement.cpp"
#include "SoFontSizeElement.cpp"
#include "SoGLAmbientColorElement.cpp"
#include "SoGLCacheContextElement.cpp"
#include "SoGLClipPlaneElement.cpp"
#include "SoGLColorIndexElement.cpp"
#include "SoGLCoordinateElement.cpp"
#include "SoGLDiffuseColorElement.cpp"
#include "SoGLDisplayList.cpp"
#include "SoGLDrawStyleElement.cpp"
#include "SoGLEmissiveColorElement.cpp"
#include "SoGLEnvironmentElement.cpp"
#include "SoGLLazyElement.cpp"
#include "SoGLLightIdElement.cpp"
#include "SoGLLightModelElement.cpp"
#include "SoGLLinePatternElement.cpp"
#include "SoGLLineWidthElement.cpp"
#include "SoGLModelMatrixElement.cpp"
#include "SoGLNormalElement.cpp"
#include "SoGLNormalizeElement.cpp"
#include "SoGLPointSizeElement.cpp"
#include "SoGLPolygonOffsetElement.cpp"
#include "SoGLPolygonStippleElement.cpp"
#include "SoGLProjectionMatrixElement.cpp"
#include "SoGLRenderPassElement.cpp"
#include "SoGLShadeModelElement.cpp"
#include "SoGLShapeHintsElement.cpp"
#include "SoGLShininessElement.cpp"
#include "SoGLSpecularColorElement.cpp"
#include "SoGLTextureCoordinateElement.cpp"
#include "SoGLTextureEnabledElement.cpp"
#include "SoGLTexture3EnabledElement.cpp"
#include "SoGLTextureImageElement.cpp"
#include "SoGLTextureMatrixElement.cpp"
#include "SoGLUpdateAreaElement.cpp"
#include "SoGLViewingMatrixElement.cpp"
#include "SoGLViewportRegionElement.cpp"
#include "SoInt32Element.cpp"
#include "SoLazyElement.cpp"
#include "SoLightAttenuationElement.cpp"
#include "SoLightElement.cpp"
#include "SoLightModelElement.cpp"
#include "SoLinePatternElement.cpp"
#include "SoLineWidthElement.cpp"
#include "SoLocalBBoxMatrixElement.cpp"
#include "SoMaterialBindingElement.cpp"
#include "SoModelMatrixElement.cpp"
#include "SoNormalBindingElement.cpp"
#include "SoNormalElement.cpp"
#include "SoOverrideElement.cpp"
#include "SoPickRayElement.cpp"
#include "SoPickStyleElement.cpp"
#include "SoPointSizeElement.cpp"
#include "SoPolygonOffsetElement.cpp"
#include "SoProfileCoordinateElement.cpp"
#include "SoProfileElement.cpp"
#include "SoProjectionMatrixElement.cpp"
#include "SoReplacedElement.cpp"
#include "SoShapeHintsElement.cpp"
#include "SoShapeStyleElement.cpp"
#include "SoShininessElement.cpp"
#include "SoSpecularColorElement.cpp"
#include "SoSwitchElement.cpp"
#include "SoTextOutlineEnabledElement.cpp"
#include "SoTextureCoordinateBindingElement.cpp"
#include "SoTextureCoordinateElement.cpp"
#include "SoTextureImageElement.cpp"
#include "SoTextureMatrixElement.cpp"
#include "SoTextureOverrideElement.cpp"
#include "SoTextureQualityElement.cpp"
#include "SoTextureScalePolicyElement.cpp"
#include "SoTransparencyElement.cpp"
#include "SoUnitsElement.cpp"
#include "SoViewVolumeElement.cpp"
#include "SoViewingMatrixElement.cpp"
#include "SoViewportRegionElement.cpp"
#include "SoWindowElement.cpp"
#include "SoListenerPositionElement.cpp"
#include "SoListenerOrientationElement.cpp"
#include "SoListenerVelocityElement.cpp"
#include "SoListenerGainElement.cpp"
