if(COIN_BUILD_LEGACY_GL_RENDERER AND UNIX AND NOT APPLE)
  find_package(X11 QUIET)
  if(X11_FOUND AND HAVE_GLX)
    add_executable(CoinGLRenderExceptionTest gl-render-exceptions/ExceptionTest.cpp)
    target_include_directories(CoinGLRenderExceptionTest PRIVATE ${X11_INCLUDE_DIR})
    target_link_libraries(CoinGLRenderExceptionTest Coin ${COIN_TARGET_LINK_LIBRARIES} ${X11_LIBRARIES})
    add_test(NAME GLRenderExceptions COMMAND CoinGLRenderExceptionTest)
    set_tests_properties(GLRenderExceptions PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 20)
  endif()
endif()
