#!/bin/bash

#Caveat emptor:
#
#-This script is based on the output generated by gcc when a specific
# header is not found, should the format change at any time in the
# future, this script is rendered useless
#
#-We assume no other includes are lacking than boost includes
#
#-We assume the boost includes are in the form of fully qualified
# includes, and not relative includes
#
#-This script needs to be called multiple times untill no errors are found.

#Notes:
#
#Before starting a series of these scripts, the following command may
#be run in the internal coin boost directory to clean it out:
#
#  find -type f -not -path '*/.svn/*' -delete
#
#To clean up afterwards:
#  svn st | egrep '^!'  | cut -d\  -f2- | xargs svn del
#  svn st | egrep '^\?'  | cut -d\  -f2- | xargs svn add
#
#To check that everything is in order, the following command should return empty:
# svn st | egrep -v '^A' | egrep -v '^D'


BASEDIR=$(pwd)
cd $(dirname $0)/..
COINDIR=$(pwd)
cd ${BASEDIR}

BUILDDIR=$1
BOOSTDIR=$2

usage() {
    echo -e "Usage is:\n\t $0 <BUILDDIR> <BOOSTDIR>";
}

#If the destination directory doesn't exist, we'll create it.
reallyCopy() {
    if ! cp $1 $2
    then
        mkdirhier $(dirname $2)
        cp $1 $2
    fi
}

if [ -z "${BUILDDIR}" ]
then
    usage
    exit 1
fi

cd ${BUILDDIR}
for file in $(make 2>&1 | egrep 'No such file or directory$' | cut -d: -f5 | cut -d/ -f2- | sort | uniq)
do
    reallyCopy ${BOOSTDIR}/$file ${COINDIR}/include/boost/$file
done
REMAINING=$(make 2>&1 | egrep 'No such file or directory$' | cut -d: -f5 | sort | uniq)
echo "${REMAINING}"
if [ -n "${REMAINING}" ]
then
    echo "${REMAINING}" | wc -l
fi
