##$ TEMPLATE Make-Common(-xxx-, -incdir-)
# **************************************************************************
# This template depends on the following variables having been set up before
# its invokation.
#
# PublicHeaders    - header files that should be installed
# PrivateHeaders   - source files that should be distributed, but not
#                    installed - including source-included source files.
# RegularSources   - source files compiled in this directory
# LinkHackSources  - alternative source files used on -enable-compact compilation
# ObsoletedHeaders - header files that should be removed upon installation

# Everything below is autogenerated from a macro, so don't modify
# within the Makefile.am itself. 19991201 mortene.

if HACKING_COMPACT_BUILD
BuildSources = $(LinkHackSources)
else
BuildSources = $(RegularSources)
endif

if BUILD_WITH_MSVC
noinst_LIBRARIES = -xxx-.lst
else
if HACKING_DYNAMIC_MODULES
lib_LTLIBRARIES = lib-xxx-@SUFFIX@LINKHACK.la
else
noinst_LTLIBRARIES = lib-xxx-.la
endif
endif

# Remove any linklibraries detected by configure, as they are not
# needed in the submodules -- only in the toplevel libCoin build.
LIBS = 

INCLUDES = -I$(top_srcdir)/include -I$(top_builddir)/src/extensions

lib-xxx-_la_SOURCES = $(BuildSources)
EXTRA_lib-xxx-_la_SOURCES = \
	$(PublicHeaders) $(PrivateHeaders) $(RegularSources) $(LinkHackSources)

lib-xxx-@SUFFIX@LINKHACK_la_SOURCES = $(BuildSources)
EXTRA_lib-xxx-@SUFFIX@LINKHACK_la_SOURCES = \
	$(PublicHeaders) $(PrivateHeaders) $(RegularSources) $(LinkHackSources)

lib-xxx-incdir = $(includedir)/Inventor/-incdir-
lib-xxx-inc_HEADERS = $(PublicHeaders)

-xxx-_lst_SOURCES = $(BuildSources)
EXTRA_-xxx-_lst_SOURCES = \
	$(PublicHeaders) $(PrivateHeaders) $(RegularSources) $(LinkHackSources)

# this rule causes a make warning, so we remove it when it is not in use
-xxx-.lst: Makefile $(-xxx-_lst_OBJECTS)
	@echo "Linking -xxx-.lst..."; \
	rm -f $@; touch $@; \
	for i in $(-xxx-_lst_OBJECTS); do echo $$i >>$@; done

install-lib-xxx-incHEADERS: $(lib-xxx-inc_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(lib-xxx-incdir)
	@list='$(lib-xxx-inc_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  src="$$d$$p"; dst="$(DESTDIR)$(lib-xxx-incdir)/$$f"; \
	  if cmp -s "$$src" "$$dst"; then :; else \
	    echo " $(INSTALL_HEADER) $$src $$dst"; \
	    $(INSTALL_HEADER) "$$src" "$$dst"; \
	  fi \
	done
	@list='$(ObsoletedHeaders)'; for f in $$list; do \
	  file="$(DESTDIR)$(lib-xxx-incdir)/$$f"; \
	  if test -x "$$file"; then \
	    echo " rm -f $$file"; \
	    rm -f "$$file"; \
	  fi \
	done

