##$ TEMPLATE Make-Common(-xxx-)

# Everything below is autogenerated from a macro, so don't modify
# within the Makefile.am itself. 19991201 mortene.

if HACKING_DYNAMIC_MODULES
lib_LTLIBRARIES = lib-xxx-@SUFFIX@LINKHACK.la
else
noinst_LTLIBRARIES = lib-xxx-.la
endif

# Remove any linklibraries detected by configure, as they are not
# needed in the submodules -- only in the toplevel libCoin build.
LIBS = 

INCLUDES = -I$(top_srcdir) -I$(top_srcdir)/include -I$(top_builddir)/include

lib-xxx-_la_SOURCES = $(ALLSOURCES)
lib-xxx-@SUFFIX@LINKHACK_la_SOURCES = $(ALLSOURCES)

lib-xxx-incdir = $(includedir)/Inventor/-xxx-
lib-xxx-inc_HEADERS = $(ALLINSTHEADERS)

