##$ TEMPLATE Make-Common(-xxx-)

# Everything below is autogenerated from a macro, so don't modify
# within the Makefile.am itself. 19991201 mortene.

if HACKING_COMPACT_BUILD
BuildSources = $(LinkHackSources)
else
BuildSources = $(RegularSources)
endif

if BUILD_WITH_MSVC
noinst_LIBRARIES = -xxx-.lst
else
if HACKING_DYNAMIC_MODULES
lib_LTLIBRARIES = lib-xxx-@SUFFIX@LINKHACK.la
else
noinst_LTLIBRARIES = lib-xxx-.la
endif
endif

# Remove any linklibraries detected by configure, as they are not
# needed in the submodules -- only in the toplevel libCoin build.
LIBS = 

INCLUDES = -I$(top_srcdir) -I$(top_srcdir)/include -I$(top_builddir)/include

lib-xxx-_la_SOURCES = $(BuildSources)
EXTRA_lib-xxx-_la_SOURCES = \
	$(PublicHeaders) $(PrivateHeaders) $(RegularSources) $(LinkHackSources)

lib-xxx-@SUFFIX@LINKHACK_la_SOURCES = $(BuildSources)
EXTRA_lib-xxx-@SUFFIX@LINKHACK_la_SOURCES = \
	$(PublicHeaders) $(PrivateHeaders) $(RegularSources) $(LinkHackSources)

-xxx-_lst_SOURCES = $(BuildSources)
EXTRA_-xxx-_lst_SOURCES = \
	$(PublicHeaders) $(PrivateHeaders) $(RegularSources) $(LinkHackSources)

lib-xxx-incdir = $(includedir)/Inventor/-xxx-
lib-xxx-inc_HEADERS = $(PublicHeaders)

-xxx-.lst: Makefile $(-xxx-_lst_OBJECTS)
	@echo "Linking -xxx-.lst..."; \
	echo $(CC) /LST:-xxx-.lst \
	  $(-xxx-_lst_OBJECTS); \
	$(CC) /LST:-xxx-.lst \
	  $(-xxx-_lst_OBJECTS);

